### ISSUE TITLE
'Named' Cache injection test failure

### ISSUE THREAD

**Issue by abhirockzz** [jcpevangelists/jcache-javaee#4]
@Inject
    @CacheContext("myNamedCache")
    Cache<String, String> articles;

    @Test
    //this fails
    public void articlesCacheIsInjectable() {
        assertNotNull(articles);
        assertNotNull(articles.getName());
        org.junit.Assert.assertEquals("myNamedCache", articles.getName());
    }

**Comment by AdamBien** [comment]
Thanks for testing, test works now. See: CustomCacheInjectionTest
